### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by orister88** [MicrosoftDocs/azure-docs.hu-hu#42]
- The right file name is AzureMfaNpsExtnConfigSetup.ps1. AzureMfs... vs. AzureMfa...
- If you are trying to Configure NPS extension with the AzureMfaNpsExtnConfigSetup.ps1 script, you will fail, if you are trying to authenticate to O365 with an MFA used account! You need an account from O365 without MFA.

---
#### A dokumentum adatai

⚠ *Ezt a szakaszt ne szerkessze. A szakasz a docs.microsoft.com ➟ GitHub-problémák hivatkozásaihoz szükséges.*

* ID: 61df48bb-a963-b1f0-8f64-b55d0bd6904c
* Version Independent ID: 677de59f-a222-8905-11c0-a3ac619d8b56
* Content: [Távoli asztali átjáró integráció az Azure MFA NPS-bővítményének](https://docs.microsoft.com/hu-hu/azure/active-directory/authentication/howto-mfa-nps-extension-rdg)
* Content Source: [articles/active-directory/authentication/howto-mfa-nps-extension-rdg.md](https://github.com/MicrosoftDocs/azure-docs.hu-hu/blob/live/articles/active-directory/authentication/howto-mfa-nps-extension-rdg.md)
* Service: **active-directory**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #16014](https://github.com/MicrosoftDocs/azure-docs/issues/16014) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hello, @orister88 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/16014.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
