### ISSUE TITLE
Incomplete code

### ISSUE THREAD

**Issue by peetronix** [MicrosoftDocs/azure-docs.hu-hu#456]
The following line is required at the end of the code to display the image: plt.show()

---
#### A dokumentum adatai

⚠ *Ezt a szakaszt ne szerkessze. A szakasz a docs.microsoft.com ➟ GitHub-problémák hivatkozásaihoz szükséges.*

* ID: 7dd31cc0-0bff-8bb0-f848-d048eb0bf53e
* Version Independent ID: 639d27af-330f-2377-72ed-47e2b913c1d9
* Content: [Rövid útmutató: Helyi kép elemzése – REST, Python - Azure Cognitive Services](https://docs.microsoft.com/hu-hu/azure/cognitive-services/computer-vision/quickstarts/python-disk#feedback)
* Content Source: [articles/cognitive-services/Computer-vision/QuickStarts/python-disk.md](https://github.com/MicrosoftDocs/azure-docs.hu-hu/blob/master/articles/cognitive-services/Computer-vision/QuickStarts/python-disk.md)
* Service: **cognitive-services**
* Sub-service: **computer-vision**
* GitHub Login: @PatrickFarley
* Microsoft Alias: **pafarley**

**Comment by srvbpigh** [comment]
Hello, @peetronix
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @peetronix 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/54479

We truly appreciate your contribution to our articles.  

Kind regards, 

Microsoft DOCS International Team
